ComputationalPhysiology/simcardems

demos/simple_demo.py, src/simcardems/cli.py, src/simcardems/datacollector.py, src/simcardems/em_model.py, src/simcardems/ep_model.py, src/simcardems/postprocess.py, src/simcardems/save_load_functions.py, src/simcardems/setup_models.py, tests/test_cli.py, tests/test_runner.py, tests/test_save_load_functions.py
The intention behind this PR was to make sure that scaling parameters where loading correctly when using load state, but I could not find any bugs with this. I added a few tests so if @IlsevanHerck could check that these tests cover the relevant issue, that would be good. 
I also refactored the datacollector class a bit so that `XDMF` files are now created as a post-processing step.
=> Fix scaling parameters

.pre-commit-config.yaml, src/simcardems/cli.py, src/simcardems/em_model.py, src/simcardems/mechanics_model.py, src/simcardems/save_load_functions.py, src/simcardems/setup_models.py
In this PR I have implemented both the backward difference scheme and the analytic scheme as suggested by @sundnes. I also added an option for the user to select the scheme he or she wants from the cli.
=> Implement backward difference and analytic schemes

.github/workflows/main.yml, demos/benchmark.py, src/simcardems/em_model.py, src/simcardems/mechanics_model.py, src/simcardems/save_load_functions.py, src/simcardems/setup_models.py
In this PR I basically create a larger function space at the PDE level and integrates the ODE at the same time as solving the PDE. This is different from how it was done before where we basically did a forward difference inside the method for computing `Ta`.
I did some simple testing of solving a PDE and ODE in this gist: https://gist.github.com/finsberg/f9dcaa8965de675219b9e5472bd4964c which is essentially the same approach as the one implemented in this PR.
=> Change the way we solve the ODEs

docs/cli.md
Fixes #87
- Update documentation : how to run in parallel + new option --show/hide_progress_bar
=> Documentation update (HPC)

docs/_toc.yml, docs/cli.md, docs/visualization.md, src/simcardems/postprocess.py
Addresses comments in ISSUE #85 
- Remove unused nodes in postprocessing
- Update documentation
-
=> Update postprocessing and documentation

src/simcardems/postprocess.py
Adress https://github.com/ComputationalPhysiology/simcardems/issues/101
=> Use xdmf.write_checkpoint instead of xdmf.write

src/simcardems/geometry.py
Address https://github.com/ComputationalPhysiology/simcardems/issues/103
=> Use constant instead of expression for default slab fibers

src/simcardems/geometry.py, src/simcardems/mechanics_model.py
Fix https://github.com/ComputationalPhysiology/simcardems/issues/135
=> Add missing external work

.github/workflows/main.yml, README.md
codecov is failing in CI for no reason, so let us use the approach outlined here: https://hynek.me/articles/ditch-codecov-python/  and here https://nedbatchelder.com/blog/202209/making_a_coverage_badge.html instead
=> Ditch codecov

.github/workflows/benchmark.yml, .github/workflows/github-pages.yml, .github/workflows/main.yml, Dockerfile, Makefile
We have created new docker images for fenics that we should use instead
https://github.com/scientificcomputing/packages/pkgs/container/fenics-gmsh
=> Update docker image

.cspell_dict.txt, src/simcardems/benchmark.py, src/simcardems/config.py, src/simcardems/datacollector.py, src/simcardems/postprocess.py, src/simcardems/runner.py, tests/test_datacollector.py
In https://github.com/ComputationalPhysiology/simcardems/pull/143 we wanted to save the benchmark results to a different file, but we need to add support for saving results to file with a different name than `results.h5` which is the purpose of this PR.
=> Custom name of output file

setup.cfg
See https://github.com/executablebooks/jupyter-book/issues/1950
=> Pin jupyterbook to avoid issue with plotly

docs/_config.yml, setup.cfg
See https://github.com/executablebooks/jupyter-book/issues/1950
=> Suppress warnings from plotly mime type

src/simcardems/config.py, src/simcardems/runner.py
Set the threshold for solving mechanics in the config file.
=> Load threshold for solving mechanics from config file

src/simcardems/postprocess.py
Extract peaks of calcium trace to assess if steady state has been reached.
=> Extract and plot peaks of calcium trace

docs/convergence_spatial.ipynb, docs/convergence_temporal.ipynb
Let the y-axis be relative deviation from the median case in order to better spot differences.
=> Fix y-axis in convergence plots

src/simcardems/postprocess.py, tests/test_postprocessing.py
Adding this option so that we for example can extract only the last beat from a huge simualtion.
=> Make it possible to extract sub results from another results file

.cspell_dict.txt, src/simcardems/models/fully_coupled_ORdmm_Land/em_model.py
Attempt to speed up interpolation between mechanics and ep mesh using PETScDMCollection
=> Speed up interpolation

src/simcardems/models/explicit_ORdmm_Land/em_model.py, src/simcardems/models/fully_coupled_Tor_Land/em_model.py
Some copy paste from #178. Should probably refactor this at some point to avoid too much duplicated code.
=> Add interpolation trick for Tord model and explicit coupled model

src/simcardems/ep_model.py, src/simcardems/models/__init__.py, src/simcardems/models/cell_model.py, src/simcardems/models/explicit_ORdmm_Land/cell_model.py, src/simcardems/models/fully_coupled_ORdmm_Land/cell_model.py, src/simcardems/models/fully_coupled_Tor_Land/cell_model.py, src/simcardems/models/pureEP_ORdmm_Land/cell_model.py
Add a new method for updating disease state.
=> Add new method for updating cell parameters after setting disease state
